"""Expose the public quant.execution package API."""

from quant.execution.alpaca_paper import (
    AlpacaMarketOrderRequest,
    AlpacaPaperBrokerClient,
    AlpacaPaperConfig,
    AlpacaTradingClientProtocol,
    map_alpaca_account_snapshot,
    map_alpaca_fill_records,
    map_alpaca_order_record,
    map_alpaca_order_status,
    map_alpaca_position,
    map_order_request_to_alpaca_market_order,
)
from quant.execution.artifacts import (
    write_dry_run_order_record,
    write_live_account_snapshot,
    write_live_fill_record,
    write_live_order_record,
    write_live_reconciliation_report,
    write_live_rehearsal_result,
    write_paper_signal_record,
    write_paper_trade_record,
)
from quant.execution.broker_adapter import (
    BrokerAdapter,
    DryRunBrokerAdapter,
    PaperBrokerAdapter,
    SignalExecutionBroker,
)
from quant.execution.dry_run_comparison import (
    compare_paper_signal_to_dry_run_order,
    latest_json,
    write_paper_dry_run_comparison_report,
)
from quant.execution.lifecycle_artifacts import (
    append_execution_event,
    claim_execution_plan_exclusive,
    current_execution_status,
    execution_dry_run_observation_path,
    execution_plan_path,
    load_broker_lookup_evidence,
    load_execution_drift_observation,
    load_execution_dry_run_observation,
    load_execution_events,
    load_execution_plan,
    write_broker_lookup_evidence,
    write_execution_drift_observation,
    write_execution_dry_run_observation,
)
from quant.execution.live_broker import (
    FakeLiveBrokerClient,
    LiveBrokerAdapter,
    LiveBrokerClient,
)
from quant.execution.live_rehearsal import (
    ALPACA_PAPER_REHEARSAL_CONFIRMATION,
    LiveRehearsalBlockedError,
    run_alpaca_paper_order_rehearsal,
)
from quant.execution.paper_broker import PaperBroker
from quant.execution.reconciliation import (
    latest_live_account_snapshot,
    load_live_fill_records,
    load_live_order_records,
    reconcile_live_state,
    reconcile_paper_state,
    write_paper_state_reconciliation_report,
)
from quant.execution.risk import (
    check_order_risk,
    check_projected_order_risk,
    check_short_sale_availability,
    opens_or_increases_short,
)
from quant.execution.safety import (
    LIVE_TRADING_CONFIRMATION,
    LiveTradingNotAllowedError,
    assert_trading_allowed,
    evaluate_trading_safety,
    load_trading_safety_config_from_env,
)
from quant.execution.semantic_paper import (
    SEMANTIC_PAPER_ACCOUNT_ID,
    SEMANTIC_PAPER_BROKER_NAME,
    SEMANTIC_PAPER_ENVIRONMENT,
    SemanticPaperBrokerAdapter,
    SemanticPaperBrokerClient,
)
from quant.execution.signal_execution import (
    decide_latest_signal,
    execute_latest_signal,
    execute_latest_signal_dry_run,
    plan_target_position_order,
)
from quant.execution.state import (
    load_paper_broker_state,
    save_paper_broker_state,
)
from quant.execution.target_alpaca_paper import (
    AlpacaSemanticTargetRunResult,
    run_alpaca_semantic_target_paper,
)
from quant.execution.target_dry_run import (
    observe_execution_plan_dry_run,
    run_semantic_target_dry_run,
)
from quant.execution.target_lifecycle import (
    ACCOUNT_WIDE_EXACT_RECONCILIATION_POLICY,
    DETECT_ONLY_DRIFT_POLICY,
    SINGLE_MARKET_ORDER_POLICY,
    claim_execution_plan,
    confirm_execution_satisfaction,
    observe_execution_drift,
    plan_target_transition_orders,
    recover_execution_submission,
    refresh_submitted_execution,
    submit_execution_plan,
    target_transition_crosses_zero,
    validate_pre_submission,
)
from quant.execution.target_paper import (
    SemanticPaperReconciliationRunner,
    SemanticPaperRunResult,
    run_semantic_target_paper,
)

__all__ = [
    "BrokerAdapter",
    "AlpacaMarketOrderRequest",
    "AlpacaPaperBrokerClient",
    "AlpacaPaperConfig",
    "AlpacaTradingClientProtocol",
    "AlpacaSemanticTargetRunResult",
    "ALPACA_PAPER_REHEARSAL_CONFIRMATION",
    "ACCOUNT_WIDE_EXACT_RECONCILIATION_POLICY",
    "DryRunBrokerAdapter",
    "DETECT_ONLY_DRIFT_POLICY",
    "FakeLiveBrokerClient",
    "LIVE_TRADING_CONFIRMATION",
    "LiveBrokerAdapter",
    "LiveBrokerClient",
    "LiveRehearsalBlockedError",
    "LiveTradingNotAllowedError",
    "PaperBroker",
    "PaperBrokerAdapter",
    "SignalExecutionBroker",
    "SINGLE_MARKET_ORDER_POLICY",
    "SEMANTIC_PAPER_ACCOUNT_ID",
    "SEMANTIC_PAPER_BROKER_NAME",
    "SEMANTIC_PAPER_ENVIRONMENT",
    "SemanticPaperBrokerAdapter",
    "SemanticPaperBrokerClient",
    "SemanticPaperRunResult",
    "SemanticPaperReconciliationRunner",
    "append_execution_event",
    "check_order_risk",
    "check_projected_order_risk",
    "check_short_sale_availability",
    "claim_execution_plan",
    "claim_execution_plan_exclusive",
    "confirm_execution_satisfaction",
    "current_execution_status",
    "execution_dry_run_observation_path",
    "opens_or_increases_short",
    "compare_paper_signal_to_dry_run_order",
    "assert_trading_allowed",
    "decide_latest_signal",
    "evaluate_trading_safety",
    "execute_latest_signal",
    "execute_latest_signal_dry_run",
    "execution_plan_path",
    "plan_target_position_order",
    "plan_target_transition_orders",
    "load_paper_broker_state",
    "latest_live_account_snapshot",
    "load_live_fill_records",
    "load_live_order_records",
    "load_broker_lookup_evidence",
    "load_execution_drift_observation",
    "load_execution_dry_run_observation",
    "load_execution_events",
    "load_execution_plan",
    "load_trading_safety_config_from_env",
    "latest_json",
    "map_alpaca_account_snapshot",
    "map_alpaca_fill_records",
    "map_alpaca_order_record",
    "map_alpaca_order_status",
    "map_alpaca_position",
    "map_order_request_to_alpaca_market_order",
    "reconcile_live_state",
    "reconcile_paper_state",
    "recover_execution_submission",
    "refresh_submitted_execution",
    "observe_execution_drift",
    "observe_execution_plan_dry_run",
    "run_semantic_target_dry_run",
    "run_semantic_target_paper",
    "run_alpaca_paper_order_rehearsal",
    "run_alpaca_semantic_target_paper",
    "save_paper_broker_state",
    "submit_execution_plan",
    "target_transition_crosses_zero",
    "validate_pre_submission",
    "write_dry_run_order_record",
    "write_live_account_snapshot",
    "write_live_fill_record",
    "write_live_order_record",
    "write_live_reconciliation_report",
    "write_live_rehearsal_result",
    "write_broker_lookup_evidence",
    "write_execution_drift_observation",
    "write_execution_dry_run_observation",
    "write_paper_dry_run_comparison_report",
    "write_paper_state_reconciliation_report",
    "write_paper_signal_record",
    "write_paper_trade_record",
]
